name: First workflow example
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: My first job
    steps:
      - name: Run my first job
        run: echo "My first job"
  second-job:
    runs-on: ubuntu-latest
    name: My second job
    needs: first-job #Job dependency, it could be a tring or an array of strings
    steps:
      - name: Run my second job part 1
        run: echo "My second job -- 1"
      - name: Run my second job part 2
        run: echo "My second job -- 1"