name: Working with directories workflow

on: push

jobs:
  working-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
        